name: Release
on:
   pull_request:
    types: [closed]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Release Type
        id: minor
        run: |
            isMinor = ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
            echo Result is $isMinor
            if [[ $isMinor ]]; then
              echo '::set-env name=RELEASE_TYPE::minor'
            fi

      - name: Release
        run: echo Release is $RELEASE_TYPE
        id: releaseStep
