name: Release
on:
   pull_request:
    types: [closed]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: array
        id: arr
        run: |
          for i in "$(${{ github.event.pull_request.labels }})"
          do
            echo label name is $i
            if [[ $i == 'major' ]]; then
              echo '::set-env name=RELEASE_TYPE::major'
            fi
            if [[ $i == 'minor' ]]; then
              echo '::set-env name=RELEASE_TYPE::minor'
            fi
            if [[ $i == 'patch' ]]; then
              echo '::set-env name=RELEASE_TYPE::patch'
            fi
          done

      - name: Release
        run: echo Release is $RELEASE_TYPE
        id: releaseStep
