name: Release
on:
   push:
    branches: [master]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Release Type
        id: minor
        run: |
            isMinor=${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
            if [[ $isMinor = "true" ]]; then
              echo '::set-env name=RELEASE_TYPE::minor'
            fi
            isMajor=${{ contains(github.event.pull_request.labels.*.name, 'major') }}
            if [[ $isMajor = "true" ]]; then
              echo '::set-env name=RELEASE_TYPE::major'
            fi
            isPatch=${{ contains(github.event.pull_request.labels.*.name, 'patch') }}
            if [[ $isPatch = "true" ]]; then
              echo '::set-env name=RELEASE_TYPE::patch'
            fi

      - name: Release
        run: echo Release is $RELEASE_TYPE
        id: releaseStep
